// <auto-generated />
namespace _09_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IntBuilding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntBuilding));
        
        string IMigrationMetadata.Id
        {
            get { return "202009021335469_IntBuilding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
